COREDIR := core/

$(OBJDIR)dc_genast.cpp.o: $(COREDIR)dc_genast.cpp
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJDIR)dc_printast.cpp.o: $(COREDIR)dc_printast.cpp
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJDIR)dc_error.cpp.o: $(COREDIR)dc_error.cpp
	$(CC) $(CFLAGS) -c -o $@ $<