COREDIR := core

$(OBJDIR)/dc_genast.cpp.o: $(COREDIR)/dc_genast.cpp
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJDIR)/dc_printast.cpp.o: $(COREDIR)/dc_printast.cpp
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJDIR)/dc_error.cpp.o: $(COREDIR)/dc_error.cpp
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJDIR)/dc_symbol.cpp.o: $(COREDIR)/dc_symbol.cpp
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJDIR)/dc_buildsym.cpp.o: $(COREDIR)/dc_buildsym.cpp
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJDIR)/dc_printsym.cpp.o: $(COREDIR)/dc_printsym.cpp
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJDIR)/dc_check.cpp.o: $(COREDIR)/dc_check.cpp
	$(CC) $(CFLAGS) -c -o $@ $<
