UTILSDIR := utils/

$(OBJDIR)dc_args.cpp.o: $(UTILSDIR)dc_args.cpp
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)dc_options.cpp.o: $(UTILSDIR)dc_options.cpp
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)dc_option_error.cpp.o: $(UTILSDIR)dc_option_error.cpp
	$(CC) $(CFLAGS) -c -o $@ $<



